[project]
name = "back"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-functions>=1.23.0",
    "xmltodict>=0.13.0",
    "docling>=2.31.0",
    "firebase-admin>=6.6.0",
]
